name: Python application
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest coverage coveralls
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Setup Database
      run: |
        mysql -h 127.0.0.1 -P 3306 -u root -proot -e "CREATE DATABASE IF NOT EXISTS testdb;"
        mysql -h 127.0.0.1 -P 3306 -u root -proot testdb < schema.sql  # Jika ada schema file
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Set PYTHONPATH to src
      run: echo "PYTHONPATH=$(pwd)/src" >> $GITHUB_ENV
    - name: Test with pytest and measure coverage
      run: |
        # Run tests with coverage measurement
        coverage run -m pytest
        # Generate coverage report
        coverage report
        # Upload coverage to Coveralls
        coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        OPENAI_API_KEY: "sk-dummy-key-for-testing"
        DB_HOST: "127.0.0.1"
        DB_PORT: "3306"
        DB_USER: "root"
        DB_PASSWORD: "root"
        DB_NAME: "testdb"
